# Site Info
title: DongKeon's blog
tagline: 'Speech Processing' 
description: 'Blog for Speech Processing'
url: http://DongKeon.github.io
#logo: '/public/logo.png'
encoding: utf-8

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty
version: 1.0.0

# About/contact
author:
  name: DongKeon
  #description: <strong>보물찾기</strong> 그리운 마을, 그 먼 바다에 이르기까지
  #gravatar: 0a638fc7996869b1b67fb90ccf77dcfe # md5 hash of your email address
  contact:
    linkedin:  https://www.linkedin.com/in/%EB%8F%99%EA%B1%B4-%EB%B0%95-0257a8161/
    github:    https://github.com/DongKeon
    facebook:  https://www.facebook.com/profile.php?id=100002211917303
    #twitter:  <hide>
    #weibo:    <hide>
    email:     mailto:dongkeon@gist.ac.kr

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Contents:           
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:          
    - '/about/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

#hero:
#  image: https://DongKeon.github.io/public/img/picture.JPG
#  caption: Original Artwork &copy; Pablo Picasso. Girl before a Mirror. Boisgeloup, March 1932. Oil on canvas

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-93172815-1' # leave blank if you don't want google analytics
disqus_short_name: 'DongKeon-github-io' # leave blank if you don't want disqus

